version: '2'
services:
  realestate-app:
    image: realestate
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://realestate-postgresql:5432/RealEstate
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://realestate-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://realestate-elasticsearch:9200
    ports:
      - 8080:8080
  realestate-postgresql:
    extends:
      file: postgresql.yml
      service: realestate-postgresql
  realestate-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: realestate-elasticsearch
